language: php

php:
    - 7.1

before_script:
    - composer update --prefer-dist

script:
    - phpunit --coverage-text

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email:
        - glim.dev@gmail.com