version: '2'

services:
    db:
        image: postgres:alpine
        volumes:
            - ${DATABASE_DATA_DIR}:/var/lib/postgresql/data
            - ${DATABASE_LOG_DIR}:/var/log/postgresql
        ports:
            - "${DATABASE_PORT}:5432"
        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_USER=${DATABASE_USER}
            - POSTGRES_DB=${DATABASE_NAME}
            - PGDATA=/var/lib/postgresql/data/pgdata

    phppgadmin:
        image: jacksoncage/phppgadmin
#        fixed fork of jacksoncage/phppgadmin
#        image: einfallstoll/phppgadmin
        ports:
            - "${PHP_PG_ADMIN_PORT}:80"
        environment:
            - POSTGRES_PORT=${DATABASE_PORT}
            - POSTGRES_DEFAULTDB=${DATABASE_NAME}
        links:
            - db:postgres

    app:
        build:
            context: ${DOCKER_DIR}/web
        ports:
            - "${HOST_PORT}:80"
        environment:
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_NAME=${DATABASE_NAME}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        volumes:
            - ${APP_DIR}:/var/www/html
            - ${COMPOSER_DIR}:/root/.composer
            - ${YARN_CACHE_DIR}:/usr/local/share/.cache/yarn/v1
            - ${APACHE_LOG_DIR}:/var/log/apache2
            - ${SYMFONY_LOG_DIR}:/var/www/html/var/logs
        links:
            - db:postgres